# Generated by Django 4.2.7 on 2023-12-04 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_social_name', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalPerson',
            fields=[
                ('professional_person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('professional_person_social_name', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('medical_appointment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appointments.patient')),
                ('professional_person_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appointments.professionalperson')),
            ],
        ),
    ]
