# Generated by Django 4.2.7 on 2023-12-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalappointment',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='medicalappointment',
            old_name='professional_person_id',
            new_name='professional_person',
        ),
    ]
